export const PERMISSIONS = {
  MANAGE_USER: 'MANAGE_USER',
  VIEW_REPORTS: 'VIEW_REPORTS',
  EDIT_TEMPLATES: 'EDIT_TEMPLATES',
  DOWNLOAD_DUA: 'DOWNLOAD_DUA',
  LOAD_FILES: 'LOAD_FILES',
  GENERATE_DUA: 'GENERATE_DUA',
  VIEW_ERROR_REPORTS: 'VIEW_ERROR_REPORTS',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
